global_settings:
  qm_bin: "/usr/sbin/qm"
  # download_image: false

template_settings:
  vmid: "9002"
  name: "Ubuntu-2404"
  linux_image: "images/noble-server-cloudimg-amd64.img"

  image_size: "10G"
  storage_pool: "local"
  ci_injectfile: "cloudConfigs/ubuntu.yaml"
  
  vm_user: "root"
  ssh_key: "ssh.key"

  debug: false